version: '3.9'

services:
  web:
    build: ./src
    ports:
      - ${WEB_PORT}:8000
    command: uvicorn server:app --host 0.0.0.0 --reload
    volumes:
      - ./src:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    command: >
      --requirepass ${REDIS_PASSWORD}
  dashboard:
    build: ./src
    command: celery --app=worker.celery --broker=redis://:${REDIS_PASSWORD}@redis:6379/0 flower --port=5555 --basic_auth=admin:${REDIS_PASSWORD}
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - web
      - redis
